import User from './modules/User.js';
import MonaNotification from './modules/Notification.js';
import Upload from './modules/upload.js';
import Team from './modules/Team.js';
import Import from './modules/Import.js';
import Test from './modules/Test.js';
User();
MonaNotification();
Upload();
Team();
Test();
Import();